/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a1.calculadora2;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import javax.swing.JTextField;
/**
 *
 * @author ALUMNOS
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        //initComponents();
       setTitle("Prueba Calculadora");
       setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       setSize(900,900);
       setLocationRelativeTo(null);
       setLayout(new GridBagLayout());
       
       GridBagConstraints gbc = new GridBagConstraints();
       gbc.weightx = 0;
       gbc.weighty = 0;
        
           //Area de calculo
        JTextField display = new JTextField(15);
        display.setEditable(false);
        gbc.gridx = 0;
        gbc.gridy = 0 ;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        getContentPane().add(display , gbc);
        
        
       gbc.gridwidth = 1;
       gbc.fill = GridBagConstraints.NONE;  
       JButton boton1 = new JButton("1"); 
       gbc.gridx = 0;
       gbc.gridy = 1;
       getContentPane().add(boton1 , gbc);
       
        
       JButton boton2 = new JButton("2"); 
       gbc.gridx = 1 ;
       gbc.gridy = 1; 
       getContentPane().add(boton2, gbc);
        
       JButton boton3 = new JButton("3"); 
       gbc.gridx = 2 ;
       gbc.gridy = 1;
       getContentPane().add(boton3, gbc);
        
       JButton boton4 = new JButton("4"); 
       gbc.gridx = 0 ;
       gbc.gridy = 2;
       getContentPane().add(boton4, gbc);
        
       JButton boton5 = new JButton("5"); 
       gbc.gridx = 1 ;
       gbc.gridy = 2;
       getContentPane().add(boton5, gbc);
        
       JButton boton6 = new JButton("6"); 
       gbc.gridx = 2 ;
       gbc.gridy = 2;
       getContentPane().add(boton6, gbc);
        
       JButton boton7 = new JButton("7"); 
       gbc.gridx = 0 ;
       gbc.gridy = 3;
       getContentPane().add(boton7, gbc);
        
       JButton boton8 = new JButton("8"); 
       gbc.gridx = 1 ;
       gbc.gridy = 3;
       getContentPane().add(boton8, gbc);
        
       JButton boton9 = new JButton("9"); 
       gbc.gridx = 2 ;
       gbc.gridy = 3;
       getContentPane().add(boton9, gbc);
        
       JButton boton0 = new JButton("0"); 
       gbc.gridx = 1 ;
       gbc.gridy = 4;
       getContentPane().add(boton0, gbc);
        
       JButton boton10 = new JButton("-"); 
       gbc.gridx = 0 ;
       gbc.gridy = 4;
       getContentPane().add(boton10, gbc);
        
       JButton boton11 = new JButton(","); 
       gbc.gridx = 2 ;
       gbc.gridy = 4;
       getContentPane().add(boton11, gbc);
        
       JButton boton12 = new JButton("+"); 
       gbc.gridx = 4 ;
       gbc.gridy = 0;
       getContentPane().add(boton12, gbc);
       
       JButton boton13 = new JButton("-"); 
       gbc.gridx = 4 ;
       gbc.gridy = 1;
       getContentPane().add(boton13, gbc);
       
       JButton boton14 = new JButton("*"); 
       gbc.gridx = 4 ;
       gbc.gridy = 2;
       getContentPane().add(boton14, gbc);
       
       JButton boton15 = new JButton("/"); 
       gbc.gridx = 4 ;
       gbc.gridy = 3;
       getContentPane().add(boton15, gbc);
       
       JButton boton16 = new JButton("="); 
       gbc.gridx = 4 ;
       gbc.gridy = 4;
       getContentPane().add(boton16, gbc);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
